### ISSUE TITLE
Release file [...] is expired (invalid since 40d 14h 46min 0s). Updates for this repository will not be applied.

### ISSUE THREAD

**Issue by sgabler** [lifeofguenter/ansible-role-php7-cli#15]
We're using this repo in one of our projects, so thank you!

Today I stumbled over this error:

    Release file for http://archive.debian.org/debian/dists/jessie-backports/InRelease is expired (invalid since 40d 14h 46min 0s). Updates for this repository will not be applied.

A writeup of what apparently happened can be found here: https://www.lucas-nussbaum.net/blog/?p=947

They suggest the following:

> Unfortunately, with the APT version in jessie, this cannot be ignored on a per source basis (it can with the APT version from stretch, using the deb [check-valid-until=no] ... syntax). So you need to disable this check globally, using:
> 
>     echo 'Acquire::Check-Valid-Until no;' > /etc/apt/apt.conf.d/99no-check-valid-until
> 
> After that, apt-get update just works.

Since I just started with Ansible, I'm not sure how to implement this in this repository, so I raised the issue first for discussion.

Glad to help if possible

**Comment by lifeofguenter** [comment]
I would not recommend using debian-jessie, but in any case, I would advise to add that fix outside of this package, as this package can not interfere with such system changes.

We did recently fix the apt-mirror to reflect on the new jessie location :)
